// Locations and Pre-configured Checkpoints Data File - Coventry UK & Disney Edition (Precision Geocoded)
window.DISNEY_PRESETS = [
    // ================= COVENTRY: CITY CENTRE =================
    { name: "Coventry Cathedral (New)", lat: 52.4082, lng: -1.5071, type: "GPS", park: "City Centre", land: "Historic Landmark" },
    { name: "St Michael's Cathedral Ruins", lat: 52.4085, lng: -1.5065, type: "GPS", park: "City Centre", land: "Historic Landmark" },
    { name: "Lady Godiva Statue (Broadgate)", lat: 52.4078, lng: -1.5097, type: "GPS", park: "City Centre", land: "Public Square" },
    { name: "Coventry Transport Museum", lat: 52.4101, lng: -1.5089, type: "GPS", park: "City Centre", land: "Museum" },
    { name: "The Wave Waterpark", lat: 52.4055, lng: -1.5126, type: "GPS", park: "City Centre", land: "Leisure / Attraction" },
    { name: "Herbert Art Gallery & Museum", lat: 52.4076, lng: -1.5056, type: "GPS", park: "City Centre", land: "Museum & Gallery" },
    { name: "St Mary's Guildhall", lat: 52.4078, lng: -1.5070, type: "GPS", park: "City Centre", land: "Historic Building" },
    { name: "Belgrade Theatre", lat: 52.4098, lng: -1.5132, type: "GPS", park: "City Centre", land: "Entertainment" },
    { name: "Holy Trinity Church", lat: 52.4087, lng: -1.5078, type: "GPS", park: "City Centre", land: "Historic Church" },
    { name: "Lower Precinct Shopping Centre", lat: 52.4081, lng: -1.5128, type: "GPS", park: "City Centre", land: "Shopping" },
    { name: "West Orchards Shopping Centre", lat: 52.4091, lng: -1.5115, type: "GPS", park: "City Centre", land: "Shopping" },
    { name: "Coventry Railway Station", lat: 52.4010, lng: -1.5135, type: "GPS", park: "City Centre", land: "Transit Hub" },
    { name: "Skydome Arena / Ice Rink", lat: 52.4068, lng: -1.5182, type: "GPS", park: "City Centre", land: "Sports & Leisure" },
    { name: "Coventry Market", lat: 52.4067, lng: -1.5138, type: "GPS", park: "City Centre", land: "Local Market" },
    { name: "The Phoenix Pub", lat: 52.4088, lng: -1.5042, type: "GPS", park: "City Centre", land: "Pub / Food" },

    // ================= COVENTRY: CV6 AREA =================
    { name: "The Craftsman Pub", lat: 52.4332, lng: -1.5268, type: "GPS", park: "CV6", land: "Pub" },
    { name: "Glentworth Fish and Chips", lat: 52.4348, lng: -1.5235, type: "GPS", park: "CV6", land: "Takeaway / Food" },
    { name: "Morrisons Parkgate Road", lat: 52.4372, lng: -1.5185, type: "GPS", park: "CV6", land: "Supermarket / Shop" },
    { name: "CBS Arena (Coventry Building Society Arena)", lat: 52.4481, lng: -1.4955, type: "GPS", park: "CV6", land: "Stadium / Arena" },
    { name: "Arena Park Shopping Centre", lat: 52.4496, lng: -1.4988, type: "GPS", park: "CV6", land: "Retail Park" },
    { name: "Keresley Jubilee Wood", lat: 52.4452, lng: -1.5385, type: "GPS", park: "CV6", land: "Nature Park" },
    { name: "The Royal Oak Keresley", lat: 52.4428, lng: -1.5360, type: "GPS", park: "CV6", land: "Pub" },
    { name: "The Hare and Hounds Keresley", lat: 52.4510, lng: -1.5398, type: "GPS", park: "CV6", land: "Pub" },
    { name: "Keresley Community Centre", lat: 52.4395, lng: -1.5332, type: "GPS", park: "CV6", land: "Community Hub" },
    { name: "Holbrooks Park", lat: 52.4335, lng: -1.5205, type: "GPS", park: "CV6", land: "Public Park" },
    { name: "The Wheel Pub Holbrooks", lat: 52.4360, lng: -1.5180, type: "GPS", park: "CV6", land: "Pub" },
    { name: "Foleshill Community Centre", lat: 52.4285, lng: -1.4982, type: "GPS", park: "CV6", land: "Community Hub" },
    { name: "Broad Street Meeting Hall", lat: 52.4250, lng: -1.4995, type: "GPS", park: "CV6", land: "Historic Venue" },
    { name: "Coventry Canal Basin", lat: 52.4140, lng: -1.5085, type: "GPS", park: "CV6", land: "Waterway / Historic" },
    { name: "Longford Park", lat: 52.4468, lng: -1.4880, type: "GPS", park: "CV6", land: "Public Park" },
    { name: "Daisychain Park", lat: 52.4310, lng: -1.5090, type: "GPS", park: "CV6", land: "Park & Playground" },

    // ================= COVENTRY: COOMBE ABBEY & BINLEY =================
    { name: "Coombe Abbey Hotel Entrance", lat: 52.4145, lng: -1.4081, type: "GPS", park: "Coombe Abbey", land: "Historic Country House" },
    { name: "Coombe Abbey Visitor Centre", lat: 52.4121, lng: -1.4110, type: "GPS", park: "Coombe Abbey", land: "Country Park" },
    { name: "Go Ape Coombe Abbey", lat: 52.4128, lng: -1.4125, type: "GPS", park: "Coombe Abbey", land: "Outdoor Activity" },
    { name: "Coombe Pool Fishing Lake", lat: 52.4115, lng: -1.4060, type: "GPS", park: "Coombe Abbey", land: "Nature Trail" },
    { name: "Coombe Abbey Heronry", lat: 52.4132, lng: -1.4035, type: "GPS", park: "Coombe Abbey", land: "Wildlife Area" },
    { name: "Binley Woods Village Hall", lat: 52.3980, lng: -1.4285, type: "GPS", park: "Binley", land: "Community Venue" },
    { name: "The Rose & Crown Binley", lat: 52.3970, lng: -1.4310, type: "GPS", park: "Binley", land: "Pub" },
    { name: "Warwickshire Shopping Park", lat: 52.3965, lng: -1.4485, type: "GPS", park: "Binley", land: "Retail Park" },
    { name: "Binley Fire Station", lat: 52.3995, lng: -1.4550, type: "GPS", park: "Binley", land: "Public Service" },

    // ================= COVENTRY: OTHER NOTABLE LOCATIONS =================
    { name: "War Memorial Park (Cenotaph)", lat: 52.3935, lng: -1.5262, type: "GPS", park: "Earlsdon", land: "Public Park" },
    { name: "University of Warwick Piazza", lat: 52.3792, lng: -1.5615, type: "GPS", park: "Gibbet Hill", land: "University Campus" },
    { name: "FarGo Village", lat: 52.4072, lng: -1.4980, type: "GPS", park: "Far Gosford", land: "Creative Quarter" },
    { name: "Charterhouse Heritage Park", lat: 52.4025, lng: -1.4925, type: "GPS", park: "London Road", land: "Historic Park" },

    // ================= DISNEY: MAGIC KINGDOM =================
    { name: "Cinderella Castle", lat: 28.4194, lng: -81.5812, type: "GPS", park: "Magic Kingdom", land: "Fantasyland / Hub" },
    { name: "Space Mountain", lat: 28.4192, lng: -81.5772, type: "GPS", park: "Magic Kingdom", land: "Tomorrowland" },
    { name: "Haunted Mansion", lat: 28.4204, lng: -81.5838, type: "GPS", park: "Magic Kingdom", land: "Liberty Square" },
    { name: "Big Thunder Mountain Railroad", lat: 28.4212, lng: -81.5852, type: "GPS", park: "Magic Kingdom", land: "Frontierland" },
    { name: "Pirates of the Caribbean", lat: 28.4181, lng: -81.5843, type: "GPS", park: "Magic Kingdom", land: "Adventureland" },
    { name: "Tiana's Bayou Adventure", lat: 28.4200, lng: -81.5851, type: "GPS", park: "Magic Kingdom", land: "Frontierland" },
    { name: "Seven Dwarfs Mine Train", lat: 28.4206, lng: -81.5807, type: "GPS", park: "Magic Kingdom", land: "Fantasyland" },
    { name: "Peter Pan's Flight", lat: 28.4201, lng: -81.5821, type: "GPS", park: "Magic Kingdom", land: "Fantasyland" },
    { name: "It's a Small World", lat: 28.4208, lng: -81.5826, type: "GPS", park: "Magic Kingdom", land: "Fantasyland" },
    { name: "Dumbo the Flying Elephant", lat: 28.4209, lng: -81.5792, type: "GPS", park: "Magic Kingdom", land: "Fantasyland (Storybook Circus)" },
    { name: "Buzz Lightyear's Space Ranger Spin", lat: 28.4185, lng: -81.5794, type: "GPS", park: "Magic Kingdom", land: "Tomorrowland" },
    { name: "Tron Lightcycle / Run", lat: 28.4211, lng: -81.5768, type: "GPS", park: "Magic Kingdom", land: "Tomorrowland" },
    { name: "Emporium Gift Shop", lat: 28.4178, lng: -81.5815, type: "GPS", park: "Magic Kingdom", land: "Main Street, U.S.A. / Shop" },
    { name: "Main Street Confectionery", lat: 28.4175, lng: -81.5810, type: "GPS", park: "Magic Kingdom", land: "Main Street, U.S.A. / Shop" },
    { name: "Cinderella's Royal Table", lat: 28.4195, lng: -81.5812, type: "GPS", park: "Magic Kingdom", land: "Fantasyland / Dining" },
    { name: "Be Our Guest Restaurant", lat: 28.4215, lng: -81.5808, type: "GPS", park: "Magic Kingdom", land: "Fantasyland / Dining" },
    { name: "Pecos Bill Tall Tale Inn & Cafe", lat: 28.4188, lng: -81.5846, type: "GPS", park: "Magic Kingdom", land: "Frontierland / Dining" },
    // Magic Kingdom Fab 50 Sculptures
    { name: "Fab 50: Mickey Mouse & Minnie Mouse", lat: 28.4189, lng: -81.5812, type: "GPS", park: "Magic Kingdom", land: "Central Hub Statue" },
    { name: "Fab 50: Donald Duck & Daisy Duck", lat: 28.4188, lng: -81.5815, type: "GPS", park: "Magic Kingdom", land: "Central Hub Statue" },
    { name: "Fab 50: Goofy & Pluto", lat: 28.4188, lng: -81.5809, type: "GPS", park: "Magic Kingdom", land: "Central Hub Statue" },
    { name: "Fab 50: Chip 'n' Dale", lat: 28.4187, lng: -81.5815, type: "GPS", park: "Magic Kingdom", land: "Central Hub Statue" },
    { name: "Fab 50: Lady and the Tramp", lat: 28.4172, lng: -81.5812, type: "GPS", park: "Magic Kingdom", land: "Town Square Statue" },
    { name: "Fab 50: Tinker Bell", lat: 28.4189, lng: -81.5816, type: "GPS", park: "Magic Kingdom", land: "Central Hub Tree Statue" },
    { name: "Fab 50: Winnie the Pooh & Piglet", lat: 28.4185, lng: -81.5826, type: "GPS", park: "Magic Kingdom", land: "Adventureland Entrance Statue" },
    { name: "Fab 50: Abu", lat: 28.4182, lng: -81.5830, type: "GPS", park: "Magic Kingdom", land: "Adventureland Sign Statue" },
    { name: "Fab 50: Orange Bird", lat: 28.4178, lng: -81.5836, type: "GPS", park: "Magic Kingdom", land: "Skipper Canteen Terrace Statue" },
    { name: "Fab 50: Stitch", lat: 28.4186, lng: -81.5796, type: "GPS", park: "Magic Kingdom", land: "Purple Wall Statue" },
    { name: "Fab 50: Dumbo & Timothy Q. Mouse", lat: 28.4196, lng: -81.5804, type: "GPS", park: "Magic Kingdom", land: "Fantasyland Castle Pathway Statue" },
    { name: "Fab 50: Jaq & Gus", lat: 28.4195, lng: -81.5809, type: "GPS", park: "Magic Kingdom", land: "Cinderella Castle Turret Statue" },
    { name: "Fab 50: Pinocchio", lat: 28.4202, lng: -81.5815, type: "GPS", park: "Magic Kingdom", land: "Fantasyland Turrets Statue" },
    { name: "Fab 50: Cogsworth & Lumiere", lat: 28.4201, lng: -81.5811, type: "GPS", park: "Magic Kingdom", land: "Fantasyland Pathway Statue" },
    { name: "Fab 50: Mad Hatter & Cheshire Cat", lat: 28.4199, lng: -81.5798, type: "GPS", park: "Magic Kingdom", land: "Mad Tea Party Statue" },

    // ================= DISNEY: EPCOT =================
    { name: "Spaceship Earth", lat: 28.3753, lng: -81.5494, type: "GPS", park: "Epcot", land: "World Celebration" },
    { name: "Guardians of the Galaxy: Cosmic Rewind", lat: 28.3742, lng: -81.5478, type: "GPS", park: "Epcot", land: "World Discovery" },
    { name: "Test Track", lat: 28.3728, lng: -81.5471, type: "GPS", park: "Epcot", land: "World Discovery" },
    { name: "Soarin' Around the World", lat: 28.3745, lng: -81.5524, type: "GPS", park: "Epcot", land: "World Nature" },
    { name: "Frozen Ever After (Norway)", lat: 28.3707, lng: -81.5484, type: "GPS", park: "Epcot", land: "World Showcase (Norway)" },
    { name: "Remy's Ratatouille Adventure (France)", lat: 28.3662, lng: -81.5532, type: "GPS", park: "Epcot", land: "World Showcase (France)" },
    // Epcot World Showcase Dining & Shops
    { name: "San Angel Inn Restaurante", lat: 28.3712, lng: -81.5478, type: "GPS", park: "Epcot", land: "World Showcase (Mexico / Dining)" },
    { name: "Plaza de los Amigos Market", lat: 28.3713, lng: -81.5477, type: "GPS", park: "Epcot", land: "World Showcase (Mexico / Shop)" },
    { name: "La Cava del Tequila", lat: 28.3711, lng: -81.5479, type: "GPS", park: "Epcot", land: "World Showcase (Mexico / Bar)" },
    { name: "Kringla Bakeri og Kafé", lat: 28.3706, lng: -81.5483, type: "GPS", park: "Epcot", land: "World Showcase (Norway / Bakery)" },
    { name: "The Fjording Gift Shop", lat: 28.3708, lng: -81.5482, type: "GPS", park: "Epcot", land: "World Showcase (Norway / Shop)" },
    { name: "Nine Dragons Restaurant", lat: 28.3698, lng: -81.5488, type: "GPS", park: "Epcot", land: "World Showcase (China / Dining)" },
    { name: "Yong Feng Shangdian Shop", lat: 28.3697, lng: -81.5486, type: "GPS", park: "Epcot", land: "World Showcase (China / Shop)" },
    { name: "Joy of Tea Kiosk", lat: 28.3701, lng: -81.5490, type: "GPS", park: "Epcot", land: "World Showcase (China / Snack)" },
    { name: "Biergarten Restaurant", lat: 28.3688, lng: -81.5488, type: "GPS", park: "Epcot", land: "World Showcase (Germany / Dining)" },
    { name: "Der Teddybär Toy Shop", lat: 28.3691, lng: -81.5489, type: "GPS", park: "Epcot", land: "World Showcase (Germany / Shop)" },
    { name: "Karamell-Küche Candy Shop", lat: 28.3693, lng: -81.5487, type: "GPS", park: "Epcot", land: "World Showcase (Germany / Bakery)" },
    { name: "Via Napoli Ristorante e Pizzeria", lat: 28.3678, lng: -81.5492, type: "GPS", park: "Epcot", land: "World Showcase (Italy / Dining)" },
    { name: "Tutto Italia Ristorante", lat: 28.3681, lng: -81.5494, type: "GPS", park: "Epcot", land: "World Showcase (Italy / Dining)" },
    { name: "La Bottega Italiana", lat: 28.3682, lng: -81.5493, type: "GPS", park: "Epcot", land: "World Showcase (Italy / Shop)" },
    { name: "Regal Eagle Smokehouse Barbecue", lat: 28.3681, lng: -81.5501, type: "GPS", park: "Epcot", land: "World Showcase (American / Dining)" },
    { name: "Art of Disney Gallery", lat: 28.3684, lng: -81.5503, type: "GPS", park: "Epcot", land: "World Showcase (American / Shop)" },
    { name: "Teppan Edo Hibachi Restaurant", lat: 28.3674, lng: -81.5508, type: "GPS", park: "Epcot", land: "World Showcase (Japan / Dining)" },
    { name: "Mitsukoshi Department Store", lat: 28.3673, lng: -81.5510, type: "GPS", park: "Epcot", land: "World Showcase (Japan / Shop)" },
    { name: "Spice Road Table", lat: 28.3670, lng: -81.5518, type: "GPS", park: "Epcot", land: "World Showcase (Morocco / Dining)" },
    { name: "Souk-al-Magreb Gift Shop", lat: 28.3668, lng: -81.5520, type: "GPS", park: "Epcot", land: "World Showcase (Morocco / Shop)" },
    { name: "Chefs de France", lat: 28.3665, lng: -81.5528, type: "GPS", park: "Epcot", land: "World Showcase (France / Dining)" },
    { name: "Les Halles Boulangerie-Patisserie", lat: 28.3661, lng: -81.5530, type: "GPS", park: "Epcot", land: "World Showcase (France / Bakery)" },
    { name: "Plume et Palette Perfume Shop", lat: 28.3666, lng: -81.5526, type: "GPS", park: "Epcot", land: "World Showcase (France / Shop)" },
    { name: "Rose & Crown Pub & Dining Room", lat: 28.3678, lng: -81.5525, type: "GPS", park: "Epcot", land: "World Showcase (UK / Pub & Dining)" },
    { name: "Yorkshire County Fish Shop", lat: 28.3679, lng: -81.5522, type: "GPS", park: "Epcot", land: "World Showcase (UK / Quick Service)" },
    { name: "The Crown & Crest Shop", lat: 28.3676, lng: -81.5528, type: "GPS", park: "Epcot", land: "World Showcase (UK / Shop)" },
    { name: "Le Cellier Steakhouse", lat: 28.3690, lng: -81.5522, type: "GPS", park: "Epcot", land: "World Showcase (Canada / Dining)" },
    { name: "Northwest Mercantile Gift Shop", lat: 28.3692, lng: -81.5520, type: "GPS", park: "Epcot", land: "World Showcase (Canada / Shop)" },
    // Epcot Fab 50 Sculptures
    { name: "Fab 50: Figment", lat: 28.3715, lng: -81.5502, type: "GPS", park: "Epcot", land: "Bridge to World Showcase Statue" },
    { name: "Fab 50: Miguel & Dante", lat: 28.3702, lng: -81.5492, type: "GPS", park: "Epcot", land: "Showcase Plaza Statue" },
    { name: "Fab 50: Rocket Raccoon & Baby Groot", lat: 28.3701, lng: -81.5495, type: "GPS", park: "Epcot", land: "Showcase Plaza Statue" },
    { name: "Fab 50: Olaf & Bruni", lat: 28.3700, lng: -81.5498, type: "GPS", park: "Epcot", land: "Showcase Plaza Statue" },
    { name: "Fab 50: Pua & Hei-Hei", lat: 28.3699, lng: -81.5501, type: "GPS", park: "Epcot", land: "Showcase Plaza Statue" },

    // ================= DISNEY: HOLLYWOOD STUDIOS =================
    { name: "Twilight Zone Tower of Terror", lat: 28.3565, lng: -81.5606, type: "GPS", park: "Hollywood Studios", land: "Sunset Boulevard" },
    { name: "Rock 'n' Roller Coaster", lat: 28.3563, lng: -81.5598, type: "GPS", park: "Hollywood Studios", land: "Sunset Boulevard" },
    { name: "Star Wars: Rise of the Resistance", lat: 28.3551, lng: -81.5627, type: "GPS", park: "Hollywood Studios", land: "Star Wars: Galaxy's Edge" },
    { name: "Millennium Falcon: Smugglers Run", lat: 28.3533, lng: -81.5628, type: "GPS", park: "Hollywood Studios", land: "Star Wars: Galaxy's Edge" },
    { name: "Toy Story Mania!", lat: 28.3561, lng: -81.5630, type: "GPS", park: "Hollywood Studios", land: "Toy Story Land" },
    { name: "Slinky Dog Dash", lat: 28.3555, lng: -81.5639, type: "GPS", park: "Hollywood Studios", land: "Toy Story Land" },
    { name: "Dok-Ondar's Den of Antiquities", lat: 28.3535, lng: -81.5622, type: "GPS", park: "Hollywood Studios", land: "Star Wars: Galaxy's Edge / Shop" },
    { name: "Oga's Cantina", lat: 28.3538, lng: -81.5624, type: "GPS", park: "Hollywood Studios", land: "Star Wars: Galaxy's Edge / Lounge" },
    { name: "The Hollywood Brown Derby", lat: 28.3572, lng: -81.5608, type: "GPS", park: "Hollywood Studios", land: "Hollywood Boulevard / Dining" },
    { name: "Tower Hotel Gifts", lat: 28.3564, lng: -81.5607, type: "GPS", park: "Hollywood Studios", land: "Sunset Boulevard / Shop" },
    // Hollywood Studios Fab 50 Sculptures
    { name: "Fab 50: Woody & Bo Peep", lat: 28.3569, lng: -81.5612, type: "GPS", park: "Hollywood Studios", land: "Animation Courtyard Statue" },
    { name: "Fab 50: R2-D2 & BB-8", lat: 28.3568, lng: -81.5615, type: "GPS", park: "Hollywood Studios", land: "Animation Courtyard Statue" },
    { name: "Fab 50: Sebastian & Flounder", lat: 28.3571, lng: -81.5610, type: "GPS", park: "Hollywood Studios", land: "Hollywood Blvd Courtyard Statue" },
    { name: "Fab 50: Joe Gardner", lat: 28.3570, lng: -81.5609, type: "GPS", park: "Hollywood Studios", land: "Hollywood Blvd Courtyard Statue" },
    { name: "Fab 50: Edna Mode", lat: 28.3567, lng: -81.5618, type: "GPS", park: "Hollywood Studios", land: "Animation Courtyard Plaza Statue" },
    { name: "Fab 50: Frozone", lat: 28.3566, lng: -81.5619, type: "GPS", park: "Hollywood Studios", land: "Animation Courtyard Plaza Statue" },

    // ================= DISNEY: ANIMAL KINGDOM =================
    { name: "Avatar Flight of Passage", lat: 28.3552, lng: -81.5925, type: "GPS", park: "Animal Kingdom", land: "Pandora - The World of Avatar" },
    { name: "Expedition Everest", lat: 28.3585, lng: -81.5872, type: "GPS", park: "Animal Kingdom", land: "Asia" },
    { name: "Kilimanjaro Safaris", lat: 28.3614, lng: -81.5912, type: "GPS", park: "Animal Kingdom", land: "Africa" },
    { name: "Tree of Life Roots", lat: 28.3579, lng: -81.5901, type: "GPS", park: "Animal Kingdom", land: "Discovery Island" },
    { name: "Tiffins Restaurant & Nomad Lounge", lat: 28.3568, lng: -81.5915, type: "GPS", park: "Animal Kingdom", land: "Discovery Island / Dining" },
    { name: "Windtraders Shop", lat: 28.3550, lng: -81.5922, type: "GPS", park: "Animal Kingdom", land: "Pandora / Shop" },
    { name: "Mombasa Marketplace", lat: 28.3608, lng: -81.5906, type: "GPS", park: "Animal Kingdom", land: "Africa / Shop" },
    // Animal Kingdom Fab 50 Sculptures
    { name: "Fab 50: Simba, Timon & Pumbaa", lat: 28.3582, lng: -81.5898, type: "GPS", park: "Animal Kingdom", land: "Discovery Island Tree Pathway Statue" },
    { name: "Fab 50: Bambi & Thumper", lat: 28.3580, lng: -81.5902, type: "GPS", park: "Animal Kingdom", land: "Discovery Island Walkway Statue" },
    { name: "Fab 50: Nemo & Dory", lat: 28.3584, lng: -81.5895, type: "GPS", park: "Animal Kingdom", land: "Discovery Island Tree Front Statue" },

    // ================= DISNEY SPRINGS =================
    { name: "World of Disney Store", lat: 28.3718, lng: -81.5173, type: "GPS", park: "Disney Springs", land: "Marketplace" },
    { name: "Aerophile Balloon Ascent", lat: 28.3705, lng: -81.5222, type: "GPS", park: "Disney Springs", land: "West Side" },
    { name: "Gideon's Bakehouse", lat: 28.3708, lng: -81.5192, type: "GPS", park: "Disney Springs", land: "The Landing" },
    { name: "The Boathouse Restaurant", lat: 28.3715, lng: -81.5204, type: "GPS", park: "Disney Springs", land: "The Landing" },
    { name: "Lego Store Giant Dragon", lat: 28.3713, lng: -81.5168, type: "GPS", park: "Disney Springs", land: "Marketplace" },
    { name: "AMC Disney Springs 24", lat: 28.3698, lng: -81.5215, type: "GPS", park: "Disney Springs", land: "West Side" },

    // ================= DISNEY RESORTS & TRANSIT HUBS =================
    { name: "Pioneer Hall (Fort Wilderness)", lat: 28.4101, lng: -81.5644, type: "GPS", park: "Disney Resorts", land: "Wilderness / Campground" },
    { name: "Grand Floridian Resort Entrance", lat: 28.4109, lng: -81.5886, type: "GPS", park: "Disney Resorts", land: "Monorail Resort" },
    { name: "Contemporary Resort Lobby", lat: 28.4158, lng: -81.5744, type: "GPS", park: "Disney Resorts", land: "Monorail Resort" },
    { name: "Polynesian Village Resort Lobby", lat: 28.4057, lng: -81.5843, type: "GPS", park: "Disney Resorts", land: "Monorail Resort" },
    { name: "Disney's Riviera Resort (Skyliner Station)", lat: 28.3658, lng: -81.5435, type: "GPS", park: "Disney Resorts", land: "Skyliner Hub" },
    { name: "Caribbean Beach Resort Skyliner Hub", lat: 28.3582, lng: -81.5438, type: "GPS", park: "Disney Resorts", land: "Skyliner Hub" },
    { name: "Art of Animation & Pop Century Skyliner", lat: 28.3508, lng: -81.5412, type: "GPS", park: "Disney Resorts", land: "Skyliner Hub" },
    { name: "Disney's BoardWalk Inn Entrance", lat: 28.3668, lng: -81.5558, type: "GPS", park: "Disney Resorts", land: "Epcot Resort Area" },
    { name: "Animal Kingdom Lodge (Jambo House)", lat: 28.3528, lng: -81.6025, type: "GPS", park: "Disney Resorts", land: "Deluxe Resort" },

    // ================= BONUS PHOTO CHALLENGES =================
    { name: "Photo with the Lady Godiva Statue", type: "BONUS_PHOTO", bonusMinDeduction: 10, park: "Bonus Challenge", land: "City Centre" },
    { name: "Photo eating a Batch / Cob from a Coventry Bakery", type: "BONUS_PHOTO", bonusMinDeduction: 10, park: "Bonus Challenge", land: "Food & Snacks" },
    { name: "Photo with a Peeping Tom Clock Scene", type: "BONUS_PHOTO", bonusMinDeduction: 10, park: "Bonus Challenge", land: "City Centre" },
    { name: "Photo feeding ducks at Coombe Abbey Lake", type: "BONUS_PHOTO", bonusMinDeduction: 10, park: "Bonus Challenge", land: "Coombe Park" },
    { name: "Photo in front of a Coventry City Sky Blues Logo", type: "BONUS_PHOTO", bonusMinDeduction: 10, park: "Bonus Challenge", land: "Sports / CBS Arena" },
    { name: "Photo with Mickey Mouse", type: "BONUS_PHOTO", bonusMinDeduction: 10, park: "Bonus Challenge", land: "Character Meet & Greet" },
    { name: "Photo with any Princess", type: "BONUS_PHOTO", bonusMinDeduction: 10, park: "Bonus Challenge", land: "Character Meet & Greet" },
    { name: "Photo with a Hidden Mickey", type: "BONUS_PHOTO", bonusMinDeduction: 10, park: "Bonus Challenge", land: "All Parks" },
    { name: "Photo eating a Mickey Pretzel or Churro", type: "BONUS_PHOTO", bonusMinDeduction: 10, park: "Bonus Challenge", land: "Dining Locations" },
    { name: "Photo riding a Monorail", type: "BONUS_PHOTO", bonusMinDeduction: 10, park: "Bonus Challenge", land: "Transportation Hubs" }
];
